version: "3.9"

services:
  front-end:
    container_name: front-end
    init: true

    networks:
      - trance-net:
    restart: always


  back-end:
    container_name: back-end
    init: true
    
    networks:
      - trance-net:
    restart: always
  

  proxy:
    image: nginx:alpine
    container_name: proxy
    
    networks:
      - trance-net:
    restart: always

  #sqlite:
  #vault:
  #monitor:

networks:
  trance-net: 
    driver: bridge
    name: inception